# Project information
site_name: Kind In Open Source
site_author: KIOSS team

repo_url: https://github.com/kind-in-open-source/kind-in-open-source.github.io/
edit_uri: blob/master/docs/

theme:
    name: material
    language: en
    features:
        - navigation.instant
        - toc.integrate
        - toc.follow
    palette:
        -   media: "(prefers-color-scheme: light)"
            scheme: default
            toggle:
                icon: material/weather-sunny
                name: Switch to dark mode
        -   media: "(prefers-color-scheme: dark)"
            scheme: slate
            toggle:
                icon: material/weather-night
                name: Switch to light mode

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

copyright:  Copyright © Contributors to the Kind In Open Source project
